---
title: "SAD- projekt 1"
fontsize: 11pt
geometry: margin=1in
---

## Autorzy

Damian Lubaszka, Jakub Sadowski

## Wykożystane pakiety i ustawiena

```{R}
require(tidyverse)
theme_set(theme_bw())
```

## Zadanie 1

Inflacja od 2020-07 do 2024-03

```{R}
infl_mies <- read_csv2("inflacja_mies.csv", locale=locale(encoding="latin1"),
 show_col_types = FALSE)
infl_mies <- infl_mies %>% filter(reprezentacja == "Poprzedni miesiac = 100")
infl_mies <- infl_mies %>% select(Rok, Miesiac,Wartosc)
infl_mies <- infl_mies %>%
  mutate(date = as.Date(sprintf("%04d-%02d-01", Rok, Miesiac)))
infl_mies <- infl_mies %>% filter(date < as.Date("2024-04-01"),
 date >= as.Date("2020-07-01"))
infl_mies <- infl_mies %>% arrange(date)

abs_value <- numeric(length(infl_mies$Wartosc))
foldable_value <- numeric(length(infl_mies$Wartosc))
inflation_col <- numeric(length(infl_mies$Wartosc))

foldable_value[1] =  100
abs_value[1] =  0
inflation_col[1] = 0

foldable_value[2] =  infl_mies$Wartosc[2]
abs_value[2] =  foldable_value[2] - 100
inflation_col[2] = infl_mies$Wartosc[2] - 100.0

for (i in 3:length(infl_mies$Wartosc)){
    foldable_value[i] <- foldable_value[i-1]/100.0 * infl_mies$Wartosc[i]
    abs_value[i] <-  foldable_value[i] - 100.0
    inflation_col[i] <- infl_mies$Wartosc[i] - 100.0
}

infl_mies$foldable_value = foldable_value
infl_mies$norm = abs_value
infl_mies$inflation = inflation_col

ggplot(data = infl_mies, aes(x=date, y =norm)) + geom_point() + 
scale_x_date(date_labels = "%Y-%m") +
 labs(x = "Rok i miesiąc", y = "Procentowy wzrost ceny względem lipca roku 2020") 
 
 ggsave("norm_inf-1.png")

```

```{R}
ggplot(data = infl_mies, aes(x=date, y = inflation)) + geom_line() + geom_point() +
scale_x_date(date_labels = "%Y-%m") +
labs(x = "Rok i miesiąc", y = "Inflacja") 

ggsave("inf-1.png")
```

```{R}
products <- read_csv2("produkty.csv", locale=locale(encoding="latin1"),
  show_col_types = FALSE)
products <- products %>% select(id_pozycja_3, wartosc, opis_okres, id_pozycja_2)
products <- products %>% mutate(year_month = as.Date(paste(substr(opis_okres, 1, 4),
substr(opis_okres, 7, 8), "01",sep = "-")))
energy <- products %>% filter(id_pozycja_3 == 5946305)
energy <- energy %>% arrange(year_month)
water <- products %>% filter(id_pozycja_3 == 5946307)
water <- water %>% arrange(year_month)
heat <- products %>% filter(id_pozycja_3 == 5946309)
heat <- heat %>% arrange(year_month)
gaz <- products %>% filter(id_pozycja_3 == 7174400)
gaz <- gaz %>% arrange(year_month)
bread <- products %>% filter(id_pozycja_2 == 5967449)
bread <- bread %>% arrange(year_month)
chicken <- products %>% filter(id_pozycja_2 == 5967456)
chicken <- chicken %>% arrange(year_month)
butter <- products %>% filter(id_pozycja_2 == 5967467)
butter <- butter %>% arrange(year_month)
eggs <- products %>% filter(id_pozycja_2 == 5967465)
eggs <- eggs %>% arrange(year_month)
cheese <- products %>% filter(id_pozycja_2 == 5967464)
cheese <- cheese %>% arrange(year_month)
```

## Oficjalna inflacja razem ze zmianami produktów

```{R}
calc_infl <- function(x) {
  infl <- numeric(length(x))
  infl[1] = 0
  for(i in 2:length(x)){
    infl[i] = x[i] * 100.0/x[i-1] - 100 
    
  }
  infl
}

normalise <- function(x) {
  normalised <- numeric(length(x))
  normalised[1] = 0
  for(i in 2:length(x)){
    normalised[i] = x[i] * 100.0/x[1] - 100
  }
  normalised
}


```

```{R}
gaz$norm = normalise(gaz$wartosc)
gaz$inflation =  calc_infl(gaz$wartosc)
heat$norm = normalise(heat$wartosc)
heat$inflation = calc_infl(heat$wartosc)
water$norm = normalise(water$wartosc)
water$inflation = calc_infl(water$wartosc)
energy$norm = normalise(energy$wartosc)
energy$inflation = calc_infl(energy$wartosc)
bread$inflation = calc_infl(bread$wartosc)
bread$norm = normalise(bread$wartosc)
eggs$inflation = calc_infl(eggs$wartosc)
eggs$norm = normalise(eggs$wartosc)
chicken$inflation = calc_infl(chicken$wartosc)
chicken$norm = normalise(chicken$wartosc)
butter$inflation = calc_infl(butter$wartosc)
butter$norm = normalise(butter$wartosc)
cheese$inflation = calc_infl(cheese$wartosc)
cheese$norm = calc_infl(cheese$wartosc)

plot_data <- tibble(date = infl_mies$date, gaz_norm = gaz$inflation,
  heat_norm = heat$inflation, water_norm = water$inflation,
  energy_norm = energy$inflation, infl_norm = infl_mies$inflation )

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = gaz_norm, color = "Gaz ziemny"),
   size = 1) +  
  geom_point(aes(y = gaz_norm, color = "Gaz ziemny")) +
  geom_line(aes(y = heat_norm, color = "Centralne ogrzewanie"), size = 1) +  
  geom_point(aes(y = heat_norm, color = "Centralne ogrzewanie")) +
  geom_line(aes(y = water_norm, color = "Ciepła woda"), size = 1) +  
  geom_point(aes(y = water_norm, color = "Ciepła woda")) +
  geom_line(aes(y = energy_norm, color = "Energia elektryczna"), size = 1) +  
  geom_point(aes(y = energy_norm, color = "Energia elektryczna")) +
  geom_line(aes(y = infl_norm, color = "Inflacja"), size = 1) +  
  geom_point(aes(y = infl_norm, color = "Inflacja")) +
  labs(x = "Rok i miesiąc", y = "%", color = "Towary") +  
  ggtitle("Inflacja towarów") + 
  scale_x_date(date_labels = "%Y-%m")
  
plot
ggsave("inflacja_towary_niejedzeniowe.png")
```

Względna różnica towary nie jedzeniowe

```{R}
plot_data <- tibble(date = infl_mies$date - infl_mies$inflation, gaz_norm = gaz$inflation - infl_mies$inflation,
  heat_norm = heat$inflation - infl_mies$inflation, water_norm = water$inflation - infl_mies$inflation,
  energy_norm = energy$inflation - infl_mies$inflation)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = gaz_norm, color = "Gaz ziemny"),
   size = 1) +  
  geom_point(aes(y = gaz_norm, color = "Gaz ziemny")) +
  geom_line(aes(y = heat_norm, color = "Centralne ogrzewanie"), size = 1) + 
  geom_point(aes(y = heat_norm, color = "Centralne ogrzewanie")) + 
  geom_line(aes(y = water_norm, color = "Ciepła woda"), size = 1) +  
  geom_point(aes(y = water_norm, color = "Ciepła woda")) +
  geom_line(aes(y = energy_norm, color = "Energia elektryczna"), size = 1) +  
  geom_point(aes(y = energy_norm, color = "Energia elektryczna"))  +
  labs(x = "Rok i miesiąc", y = "%", color = "Towary") +  
  ggtitle("Względna różnica pomiędzy inflacją a inflacją rzeczywistą produktów") + 
  
  scale_x_date(date_labels = "%Y-%m")
  
plot
ggsave("r_wzgl_towary_nie_jedz.png")
```

Wykres inflacjii dla produktów spożywczych 1

```{R}
plot_data <- tibble(date = infl_mies$date, chicken_i = chicken$inflation,
  butter_i = butter$inflation, cheese_i = cheese$inflation,
  eggs_i = eggs$inflation, bread_i = bread$inflation, infl_i = infl_mies$inflation)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = cheese_i, color = "Ser "),
   size = 1) +
  geom_line(aes(y = bread_i, color = "Chleb"), size = 1) + 
  geom_point(aes(y = bread_i, color = "Chleb")) +
  geom_line(aes(y = butter_i, color = "Masło"), size = 1) +  
  geom_point(aes(y = butter_i, color = "Masło")) + 
  geom_point(aes(y = cheese_i, color = "Ser ")) +
  geom_line(aes(y = infl_i, color = "Inflacja"), size = 1) +  
  geom_point(aes(y = infl_i, color = "Inflacja")) +
  labs(x = "Rok i miesiąc", y = "%", color = "Towary") +  
  ggtitle("Inflacja towarów") 
  
plot
ggsave("infl_towary_jedze1.png")
```

Wykres inflacjii dla produktów spożywczych 2

```{R}
plot_data <- tibble(date = infl_mies$date, chicken_i = chicken$inflation,
  butter_i = butter$inflation, cheese_i = cheese$inflation,
  eggs_i = eggs$inflation, bread_i = bread$inflation, infl_i = infl_mies$inflation)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = eggs_i, color = "Jaja kurze"), size = 1) +  
  geom_point(aes(y = eggs_i, color = "Jaja kurze")) +
  geom_line(aes(y = chicken_i, color = "Kurczęta"), size = 1) +
  geom_point(aes(y = chicken_i, color = "Kurczęta")) +
  geom_line(aes(y = infl_i, color = "Inflacja"), size = 1) +  
  geom_point(aes(y = infl_i, color = "Inflacja")) +
  labs(x = "Rok i miesiąc", y = "%", color = "Towary") +  
  ggtitle("Inflacja towarów") 
  
plot
ggsave("infl_towary_jedze2.png")
```

Względna różnica pomiędzy inflacją a inflacją rzeczywistą produktów.

```{R}
plot_data <- tibble(date = infl_mies$date, chicken_i = chicken$inflation - infl_mies$inflation,
  butter_i = butter$inflation - infl_mies$inflation, cheese_i = cheese$inflation - infl_mies$inflation,
  eggs_i = eggs$inflation - infl_mies$inflation, bread_i = bread$inflation - infl_mies$inflation)

plot <- ggplot(plot_data, aes(date)) + 
   geom_line(aes(y = eggs_i, color = "Jaja kurze"), size = 1) +  
  geom_point(aes(y = eggs_i, color = "Jaja kurze")) +
  geom_line(aes(y = chicken_i, color = "Kurczęta"), size = 1) +
  geom_point(aes(y = chicken_i, color = "Kurczęta")) +
  geom_line(aes(y = cheese_i, color = "Ser "),
   size = 1) +
  geom_point(aes(y = cheese_i, color = "Ser ")) +
  geom_line(aes(y = bread_i, color = "Chleb"), size = 1) + 
  geom_point(aes(y = bread_i, color = "Chleb")) +
  geom_line(aes(y = butter_i, color = "Masło"), size = 1) +  
  geom_point(aes(y = butter_i, color = "Masło")) + 
  labs(x = "Rok i miesiąc", y = "%", color = "Towary") + 
  ggtitle("Względna różnica pomiędzy inflacją a inflacją rzeczywistą produktów") 
  
plot
ggsave("r_wzgl_towary_jedz.png")
```

Wartość koszyka wynikająca z inflacjii i wartość rzeczywista produktów niejedzeniowe

```{R}
trolley = gaz$wartosc + heat$wartosc + water$wartosc + energy$wartosc
infl_trolley<- numeric(length(infl_mies$inflation))
infl_trolley[1] = trolley[1]
 for(i in 2:length(infl_mies$inflation)){
    infl_trolley[i] = infl_trolley[i-1] + infl_trolley[i-1] * infl_mies$inflation[i]/100.0
  }

plot_data <- tibble(date = infl_mies$date, tr = trolley, infl_tr = infl_trolley)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = tr, color = "Rzeczywista wartość produktów niejedzeniowych"), size = 1) +  
  geom_point(aes(y = tr, color = "Rzeczywista wartość produktów niejedzeniowych")) +
  geom_line(aes(y = infl_tr, color = "Wartość produktów niejedzeniowych z inflacjii"), size = 1) +  
  geom_point(aes(y = infl_tr, color = "Wartość produktów niejedzeniowych z inflacjii")) +
  labs(x = "Rok", y = "Wartość [zł]", color = "") +  
  ggtitle("Wartość koszyka wynikająca z inflacjii i wartość rzeczywista produktów 
  niejedzeniowe") + 
  theme(legend.position = "bottom") 
plot
ggsave("koszyki_pr_niejedz.png")
```

Wykresy koszyka dla produktów spożywczych

```{R}
trolley = bread$wartosc + eggs$wartosc + chicken$wartosc + butter$wartosc + cheese$wartosc
infl_trolley<- numeric(length(infl_mies$inflation))
infl_trolley[1] = trolley[1]
 for(i in 2:length(infl_mies$inflation)){
    infl_trolley[i] = infl_trolley[i-1] + infl_trolley[i-1] * infl_mies$inflation[i]/100.0
  }

plot_data <- tibble(date = infl_mies$date, tr = trolley, infl_tr = infl_trolley)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = tr, color = "Rzeczywista wartość produktów jedzeniowych"), size = 1) +  
  geom_point(aes(y = tr, color = "Rzeczywista wartość produktów jedzeniowych")) +
  geom_line(aes(y = infl_tr, color = "Wartość produktów jedzeniowych z inflacjii"), size = 1) +  
  geom_point(aes(y = infl_tr, color = "Wartość produktów jedzeniowych z inflacjii")) +
  labs(x = "Rok", y = "Wartość [zł]", color = "") +  
  ggtitle("Wartość koszyka wynikająca z inflacjii i wartość rzeczywista produkty
  jedzeniowe") + 
  theme(legend.position = "bottom") 
plot
ggsave("koszyki_pr_jedz.png")
```

Wykres znormalizowanego wzrostu ceny dla produktów spożywczych

```{R}
plot_data <- tibble(date = infl_mies$date, chicken_i = chicken$norm,
  butter_i = butter$norm, cheese_i = cheese$norm,
  eggs_i = eggs$norm, bread_i = bread$norm, infl_i = infl_mies$norm)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = cheese_i, color = "Ser "),
   size = 1) +  
  geom_line(aes(y = bread_i, color = "Chleb"), size = 1) +  
  geom_line(aes(y = eggs_i, color = "Jaja kurze"), size = 1) +  
  geom_line(aes(y = butter_i, color = "Masło"), size = 1) +  
  geom_line(aes(y = chicken_i, color = "Kurczęta patroszone"), size = 1) +
  geom_line(aes(y = infl_i, color = "Inflacja"), size = 1) +  
  labs(x = "Rok i miesiąc", y = "", color = "Towary") +  
  ggtitle("Zmiany cen") 

plot

ggsave("norm_zm_jedz.png")
```

Wykres dla znormailzowanego wzrostu cen produktów nieżywnościowych

```{R}
plot_data <- tibble(date = infl_mies$date, gaz_norm = gaz$norm,
  heat_norm = heat$norm, water_norm = water$norm,
  energy_norm = energy$norm, infl_norm = infl_mies$norm )

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = gaz_norm, color = "Gaz ziemny wysokometanowy z sieci "),
   size = 1) +  
  geom_line(aes(y = heat_norm, color = "Centralne ogrzewanie"), size = 1) +  
  geom_line(aes(y = water_norm, color = "Ciepła woda"), size = 1) +  
  geom_line(aes(y = energy_norm, color = "Energia elektryczna"), size = 1) +  
  geom_line(aes(y = infl_norm, color = "Inflacja"), size = 1) +  
  labs(x = "Rok i miesiąc", y = "", color = "Towary") +  
  ggtitle("Zmiany cen") + 
  theme(
    legend.position = c(.40, .95),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(1, 1, 1, 1)
    ) +
  scale_x_date(date_labels = "%Y-%m")
  
plot

ggsave("norm_zm_niejedz.png")
```

## Zadanie 2

Inflacja oraz nakład na badania i rozwój dla lat od 2000-2022

```{R}
infl = read_csv2("inflacja.csv", locale=locale(encoding="latin1"),
  show_col_types = FALSE)
infl = infl %>% select(Rok, Wartosc)
infl = infl %>% arrange(Rok)

infl %>% mutate(inflation = infl$Wartosc - 100)
modif_inflation <- tibble(rok = infl$Rok, wartosc=infl$Wartosc) 

modif_inflation  <- modif_inflation  %>% filter(rok >= 1999, rok <= 2022)


abs_value <- numeric(length(modif_inflation$wartosc))
foldable_value <- numeric(length(modif_inflation$wartosc))

foldable_value[1] =  100
abs_value[1] =  0

foldable_value[2] =  modif_inflation$wartosc[2]
abs_value[2] =  foldable_value[2] - 100

for (i in 3:length(modif_inflation$wartosc)){
    foldable_value[i] <- foldable_value[i-1]/100.0 * modif_inflation$wartosc[i]
    abs_value[i] <-  foldable_value[i] - 100.0
}

modif_inflation$foldable_value = foldable_value
modif_inflation$norm = abs_value
modif_inflation$inflation = modif_inflation$wartosc - 100

ggplot(data = modif_inflation , aes(x=rok, y = norm)) + geom_point() + 
  labs(x = "Rok", y = "Inflacja") +
  ggtitle("Znormalizowany wzrost ceny na podstawie inflacji lata 2000-2022")

 ggsave("norm_inf-2.png")


```

```{R}
ggplot(data = modif_inflation , aes(x=rok, y = inflation)) + geom_line() + geom_point()
  labs(x = "Rok", y = "Inflacja [%]")

 ggsave("inf-2.png")

```

```{R}
brp = read_csv2("brp.csv", , show_col_types = FALSE)
bp = brp %>% select(id_pozycja_2, id_daty, wartosc, id_przekroj)
bp = brp %>% filter(id_pozycja_2 == 660892)
bp = bp %>% arrange(id_daty)
prod = brp %>% filter(id_przekroj == 16)
prod = prod %>% arrange(id_daty)
bp = bp %>% mutate(wart_calk = prod$wartosc * wartosc)
gov = brp %>% filter(id_pozycja_2 == 546159)
gov = gov %>% arrange(id_daty)
gov = gov %>% mutate(wart_calk = prod$wartosc * wartosc)
bes = brp %>% filter(id_pozycja_2 == 546157)
bes = bes %>% arrange(id_daty)
bes = bes %>% mutate(wart_calk = prod$wartosc * wartosc)
hes = brp %>% filter(id_pozycja_2 == 546167)
hes = hes %>% arrange(id_daty)
hes = hes %>% mutate(wart_calk = prod$wartosc * wartosc)
ggplot(data = bp, aes(x=id_daty, y = wart_calk)) + geom_point() + geom_line() +
labs(x = "Rok", y = "Wartość [mln zł]") +
  ggtitle("Wykres nakładu na badania i rozwój w poszczególnych latach")
```

## Nałożone na siebie wartości inflacji oraz nakładów na badania i rozwój

```{R}
bp$norm = normalise(bp$wart_calk)
bp$inflation = calc_infl(bp$wart_calk)

plot_data <- tibble(date = modif_inflation$rok, infl_norm = modif_inflation$inflation, b_norm = bp$inflation)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = b_norm, color = "Badania i rozwój"), size = 1) +  
  geom_point(aes(y = b_norm, color = "Badania i rozwój")) +
  geom_line(aes(y = infl_norm, color = "Inflacja"), size = 1) +  
  geom_point(aes(y = infl_norm, color = "Inflacja")) +
  labs(x = "Rok", y = "%", color = "") +  
  ggtitle("Inflacja nakładów na badania i rozwój oraz inflacja") + 
  theme(legend.position = "bottom")
plot
ggsave("badania_rozw_infl.png")
```

Różne sektory

```{R}
plot_data <- tibble(date = hes$id_daty, hes = hes$wart_calk, gov = gov$wart_calk, bes = bes$wart_calk, og = bp$wart_calk)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = hes, color = "Hes"), size = 1) +  
  geom_point(aes(y = hes, color = "Hes")) +
  geom_line(aes(y = bes, color = "Bes"), size = 1) +  
  geom_point(aes(y = bes, color = "Bes")) +
  geom_line(aes(y = gov, color = "GOV"), size = 1) +
  geom_point(aes(y = gov, color = "GOV")) +
  geom_line(aes(y = og, color = "Całkowita"), size = 1) +  
  geom_point(aes(y = og, color = "Całkowita")) +
  labs(x = "Rok", y = "Wartość [mln zł]", color = "") +  
  ggtitle("Nakłady na poszczególne sektory") + 
  theme(legend.position = "bottom") 
plot
ggsave("bR_sektory.png")
```

Wykres z procentową zmianą ceny

```{R}
plot_data <- tibble(date = modif_inflation$rok, infl_norm = modif_inflation$norm, b_norm = bp$norm)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = b_norm, color = "Badania i rozwój"), size = 1) +  
  geom_point(aes(y = b_norm, color = "Badania i rozwój")) +
  geom_line(aes(y = infl_norm, color = "Inflacja"), size = 1) +  
  geom_point(aes(y = infl_norm, color = "Inflacja"))+
  labs(x = "Rok", y = "%", color = "") +  
  ggtitle("Nakłady na badania i rozwój oraz inflacja") + 
  theme(legend.position = "bottom")
plot
```

Wartość b+r wynikająca z infl

```{R}

infl_trolley<- numeric(length(modif_inflation$inflation))
infl_trolley[1] = bp$wart_calk[1]
 for(i in 2:length(modif_inflation$inflation)){
    infl_trolley[i] = infl_trolley[i-1] + infl_trolley[i-1] * modif_inflation$inflation[i]/100.0
  }

plot_data <- tibble(date = modif_inflation$rok, tr = bp$wart_calk, infl_tr = infl_trolley)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = tr, color = "Rzeczywista wartość przeznaczona na B+R"), size = 1) +  
  geom_point(aes(y = tr, color = "Rzeczywista wartość przeznaczona na B+R")) +
  geom_line(aes(y = infl_tr, color = "Wartość B+R z inflacjii"), size = 1) +  
  geom_point(aes(y = infl_tr, color = "Wartość B+R z inflacjii")) +
  labs(x = "Rok", y = "Wartość [mln zł]", color = "") +  
  ggtitle("Nakłady na badania i rozwój oraz inflacja") + 
  theme(legend.position = "bottom") 
plot
ggsave("br_i_infl.png")
```

## Zadanie 3

Inflacja w kwartałach od 2020 do 2024

```{R}
infl_mies_3 <- read_csv2("inflacja_mies.csv", locale=locale(encoding="latin1"),
 show_col_types = FALSE)
infl_mies_3 <- infl_mies_3 %>% filter(reprezentacja == "Poprzedni miesiac = 100")
infl_mies_3 <- infl_mies_3 %>% select(Rok, Miesiac,Wartosc)
infl_mies_3 <- infl_mies_3 %>%
  mutate(date = as.Date(sprintf("%04d-%02d-01", Rok, Miesiac)))
infl_mies_3 <- infl_mies_3 %>% filter(date <= as.Date("2023-12-01"),
 date >= as.Date("2020-01-01"))
infl_mies_3 <- infl_mies_3 %>% arrange(date)
infl_mies_3$opis_okres <- paste0(infl_mies_3$Rok, " Q", ceiling(infl_mies_3$Miesiac / 3))
infl_q <- data.frame(opis_okres = character(), wartosc = numeric())

for (q in unique(infl_mies_3$opis_okres)) {
 data_q <- infl_mies_3 %>% filter(opis_okres == q)
 value <- data_q$Wartosc[1] * data_q$Wartosc[2] * data_q$Wartosc[3] / 10000.0
 infl_q <- rbind(infl_q, data.frame(opis_okres = q, wartosc = value))
}

```

```{R}
calculate_inflation <- function(data) {
  abs_value <- numeric(length(data$wartosc))
  foldable_value <- numeric(length(data$wartosc))
  inflation_col <- numeric(length(data$wartosc))

  foldable_value[1] <- data$wartosc[1]
  abs_value[1] <- foldable_value[1] - 100
  inflation_col[1] <- data$wartosc[1] - 100.0
  
  for (i in 2:length(data$wartosc)) {
    foldable_value[i] <- foldable_value[i-1] / 100.0 * data$wartosc[i]
    abs_value[i] <- foldable_value[i] - 100.0
    inflation_col[i] <- data$wartosc[i] - 100.0
  }
  
  data$foldable_value <- foldable_value
  data$norm <- abs_value
  data$inflation <- inflation_col
  
  return(data)
}
```

```{R}
m = read_csv2("mieszkania.csv", locale=locale(encoding="latin1"), col_types = cols(wartosc = "n"), show_col_types = FALSE)

m_wt_ws = m %>% select(id_pozycja_2, opis_okres, wartosc, id_przekroj)
m_wt_ws = m_wt_ws %>% filter(id_przekroj == 484)
m_wt_ws = m_wt_ws %>% filter(id_pozycja_2 == 4801796)
m_wt_ws <- m_wt_ws %>% select(-id_przekroj, -id_pozycja_2)
m_wt_ws = m_wt_ws %>% arrange(opis_okres)

m_pie_ws = m %>% select(id_pozycja_2, opis_okres, wartosc, id_przekroj)
m_pie_ws = m_pie_ws %>% filter(id_przekroj == 484)
m_pie_ws = m_pie_ws %>% filter(id_pozycja_2 == 4801795)
m_pie_ws <- m_pie_ws %>% select(-id_przekroj, -id_pozycja_2)
m_pie_ws = m_pie_ws %>% arrange(opis_okres)

m_wt_med = m %>% select(id_pozycja_2, opis_okres, wartosc, id_przekroj)
m_wt_med = m_wt_med %>% filter(id_przekroj == 485)
m_wt_med = m_wt_med %>% filter(id_pozycja_2 == 4801796)
m_wt_med <- m_wt_med %>% select(-id_przekroj, -id_pozycja_2)
m_wt_med = m_wt_med %>% arrange(opis_okres)

m_pie_med = m %>% select(id_pozycja_2, opis_okres, wartosc, id_przekroj)
m_pie_med = m_pie_med %>% filter(id_przekroj == 485)
m_pie_med = m_pie_med %>% filter(id_pozycja_2 == 4801795)
m_pie_med <- m_pie_med %>% select(-id_przekroj, -id_pozycja_2)
m_pie_med = m_pie_med %>% arrange(opis_okres)

```

```{R}

infl_q <- calculate_inflation(infl_q)
infl_q =  infl_q %>% arrange(opis_okres)
m_pie_ws <- calculate_inflation(m_pie_ws)
m_wt_ws <- calculate_inflation(m_wt_ws)

```

Inflacja w poszczególnych kwartałach

```{R}

plot_data <- tibble(date = infl_q$opis_okres, infl_q_inf= infl_q$inflation, m_pie_ws_inf= m_pie_ws$inflation, m_wt_ws_inf= m_wt_ws$inflation)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = infl_q_inf, color = "Inflacja cen towarów i usług", group = 1), size = 1) +  
  geom_point(aes(y = infl_q_inf, color = "Inflacja cen towarów i usług")) +
  geom_line(aes(y = m_pie_ws_inf, color = "Inflacja na rynku pierwotnym", group = 1), size = 1) +  
  geom_point(aes(y = m_pie_ws_inf, color = "Inflacja na rynku pierwotnym")) +
  geom_line(aes(y = m_wt_ws_inf, color = "Inflacja na rynku wtórnym", group = 1), size = 1) +  
  geom_point(aes(y = m_wt_ws_inf, color = "Inflacja na rynku wtórnym")) +
  labs(x = "Kwartał", y = "[%]", color = "") +  
  ggtitle("Inflacja w poszczególnych kwartałach") + 
  theme(legend.position = "bottom") +
  scale_x_discrete(breaks = unique(plot_data$date)[seq(1, length(unique(plot_data$date)), by = 2)])

plot
ggsave("3_inf.png")

```

Unormowana inflacja w poszczególnych kwartałach

```{R}

plot_data <- tibble(date = infl_q$opis_okres, infl_q_inf= infl_q$norm, m_pie_ws_inf= m_pie_ws$norm, m_wt_ws_inf= m_wt_ws$norm)
plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = infl_q_inf, color = "Inflacja cen towarów i usług", group = 1), size = 1) +  
  geom_point(aes(y = infl_q_inf, color = "Inflacja cen towarów i usług")) +
  geom_line(aes(y = m_pie_ws_inf, color = "Inflacja na rynku pierwotnym", group = 1), size = 1) +  
  geom_point(aes(y = m_pie_ws_inf, color = "Inflacja na rynku pierwotnym")) +
  geom_line(aes(y = m_wt_ws_inf, color = "Inflacja na rynku wtórnym", group = 1), size = 1) +  
  geom_point(aes(y = m_wt_ws_inf, color = "Inflacja na rynku wtórnym")) +
  labs(x = "Kwartał", y = "Procentowy wzrost cen", color = "") +  
  ggtitle("Inflacja w poszczególnych kwartałach") + 
  theme(legend.position = "bottom") +
  scale_x_discrete(breaks = unique(plot_data$date)[seq(1, length(unique(plot_data$date)), by = 2)])

plot
ggsave("3_inf_norm.png")

```

```{R}
m_wt_med$norm = normalise(m_wt_med$wartosc)
m_wt_med$inflation =  calc_infl(m_wt_med$wartosc)
m_pie_med$norm = normalise(m_pie_med$wartosc)
m_pie_med$inflation = calc_infl(m_pie_med$wartosc)

```

```{R}
plot_data <- tibble(date = infl_q$opis_okres, m_pie_med_wartosc= m_pie_med$wartosc, m_wt_med_wartosc= m_wt_med$wartosc)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = m_pie_med_wartosc, color = "Rynek pierwotny", group = 1), size = 1) +  
  geom_point(aes(y = m_pie_med_wartosc, color = "Rynek pierwotny")) +
  geom_line(aes(y = m_wt_med_wartosc, color = "Rynek wtórny", group = 1), size = 1) +  
  geom_point(aes(y = m_wt_med_wartosc, color = "Rynek wtórny")) +
  labs(x = "Kwartał", y = "[zł / m ^ 2] ", color = "") +  
  ggtitle("Mediana cen lokali") + 
 
  scale_x_discrete(breaks = unique(plot_data$date)[seq(1, length(unique(plot_data$date)), by = 2)])

plot
ggsave("3_med.png")
```

Inflacja w poszczególnych kwartałach dla mediany cen za metr kwadratowy w porównaniu z oryginalną inflacją

```{R}

plot_data <- tibble(date = infl_q$opis_okres, infl_q_norm= infl_q$norm, m_pie_med_norm= m_pie_med$norm, m_wt_med_norm= m_wt_med$norm)

plot <- ggplot(plot_data, aes(date)) + 
  geom_line(aes(y = infl_q_norm, color = "Inflacja cen towarów i usług", group = 1), size = 1) +  
  geom_point(aes(y = infl_q_norm, color = "Inflacja cen towarów i usług")) +
  geom_line(aes(y = m_pie_med_norm, color = "Inflacja na rynku pierwotnym", group = 1), size = 1) +  
  geom_point(aes(y = m_pie_med_norm, color = "Inflacja na rynku pierwotnym")) +
  geom_line(aes(y = m_wt_med_norm, color = "Inflacja na rynku wtórnym", group = 1), size = 1) +  
  geom_point(aes(y = m_wt_med_norm, color = "Inflacja na rynku wtórnym")) +
  labs(x = "Kwartał", y = "Procentowy wzrost cen", color = "") +  
  ggtitle("Inflacja w poszczególnych kwartałach") + 
 
  scale_x_discrete(breaks = unique(plot_data$date)[seq(1, length(unique(plot_data$date)), by = 2)])

plot
ggsave("3_inf_norm_med.png")

```
